name: Sanity Check

on: [push, pull_request]

jobs:
  make_check:
    name: check for issues in the collection_scripts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: sudo apt-get install -y make
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run ShellCheck
        run: make check
      - name: Run PyTest
        run: make pytest
